### PR TITLE
Move `OUT/PWURS/-T` from `dict.json` to `condensed-strokes.json`

### PR DESCRIPTION
**Pull request by paulfioravanti**
This PR is minor housekeeping; proposing to move `OUT/PWURS/-T` from `dict.json` to `condensed-strokes.json`, since it is not an "official" Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) outline, but does output "outburst" as expected.

### CODE REVIEW

**Comment by didoesdigital** [comment]
Hmm, it looks like an entry we could improve while we move it. I'm thinking `AOUT/PWUFRT` using the prefix for out^ and the inversion brief for burst. Alternatively, there's the `*S` as "st" option: `AOUT/PW*URS`

**Comment by paulfioravanti** [comment]
I'd say that keeping `OUT/PWURS/-T` in `condensed-strokes.json`, as well as adding both `AOUT/PWUFRT` and `AOUT/PW*URS` to it would be fine since they all output the expected result.

If I was going to choose one of the latter two outlines to replace the current entry in the Gutenberg dictionary, I think I'd probably pick `AOUT/PWUFRT`. They're both about as easy as each other to stroke, and even though `AOUT/PWUFRT` has inversion, there may be some confusion around `*S` as "st" in `AOUT/PW*URS` (I had to look it up, and couldn't find it in Learn Plover! and in Plover itself there's only the `*FT` entry for "{^st}".

What do you think?

**Comment by didoesdigital** [comment]
That all sounds good to me, including the preference for the Gutenberg dictionary.

I was wondering where ` *S` as "st" came from as I was writing it. I think it might be borrowed from Phoenix theory? I believe Plover's dictionary sometimes resorts to that pattern when nothing else from Plover theory fits e.g. `"HRO*S": "lost",`

```
"HROS": "loss",
"HROFT": "lot of",
"HRO*FT": "loft",
"HROTS": "lots",
```

**Comment by paulfioravanti** [comment]
Thanks for the feedback, @didoesdigital! Changes done!

**Pull request merged**
