### PR TITLE
Re-shuffle outlines for "Shakespeare"

### PR DESCRIPTION
**Pull request by paulfioravanti**
This PR proposes the following:

- Move `SHAEUBG/-S/SPAOER` from `dict.json` to `condensed-strokes.json`
  since it is not an outline in Plover but still outputs the expected result
- Move `SHAEUBG/PAOER` from `dict.json` to `bad-habits.json` due to
  missing an `S` stroke, resulting in "Shakepeare"
- Move `SPAEUBG/SPHAOER` from `dict.json` to `bad-habits.json` due to a
  strange pronunciation of "Spakesmeare"
- Choose `SHAEUBG/SPAOER` as the "most correct" outline for usage in the Gutenberg dictionary

### CODE REVIEW

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti . That mostly looks good though I can see `plover/assets/main.json:92553:2:"SHAEUBG/-S/SPAOER": "Shakespeare",` so I don't think we need to move it to `condensed-strokes.json`. Would you also please fix up the conflicts?

**Comment by paulfioravanti** [comment]
Yep, I'll fix up the conflicts and re-submit.

I guess that `"SHAEUBG/-S/SPAOER": "Shakespeare"` was added after Plover [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) was released, since doing a search for "Shakespeare" nets only the following outlines:

```
Shakespeare:
   SHAEUBG/PAOER
   SHAEUBG/SPAER
   SHAEUBGS/PAER
   SHAUBG/SPAOER
   SHAEUBG/SPAOER
   SHAEUBGS/PAOER
   SHA*EUBG/SPAOER
   SHAEUBGS/SPAOER
   SPAEUBG/SPHAOER
   SHA*EUBGS/SPAOER
```

Nevertheless, since it would seem that `"SHAEUBG/-S/SPAOER": "Shakespeare"` will be in the next release, I'll leave it alone in `dict.json`.

**Comment by paulfioravanti** [comment]
Done ✅

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti ! 

I did some digging and it turns out Plover only shows 10 entries in the lookup dialog ([code here](https://github.com/openstenoproject/plover/blob/685bd3373dcf19817f59070274a33457ff145701/plover/gui_qt/suggestions_dialog.py#L127-L131)), which explains why `"SHAEUBG/-S/SPAOER": "Shakespeare"` didn't appear.

**Comment by didoesdigital** [comment]
Worst case scenario is [quadruplicate](https://didoesdigital.com/typey-type/lookup?q=quadruplicate):

image

**Comment by paulfioravanti** [comment]
Yikes to the quadruplicate entry! And thanks for the heads up about that hard limit of 10 results per search. Hopefully that'll become a config option in a future version of Plover.

**Pull request merged**
