### PR TITLE
Add condensed strokes fingerspelled dictionary

### PR DESCRIPTION
**Pull request by paulfioravanti**
Related to [this comment](https://github.com/didoesdigital/steno-dictionaries/issues/510#issuecomment-671218294) in #510.

This PR proposes to split the condensed strokes dictionary into two dictionaries: `condensed-strokes.json` and `condensed-strokes-fingerspelled.json`, where the latter is for outlines that are fingerspelled.

For `condensed-strokes-fingerspelled.json`, I decided to define "fingerspelled" as being "100% fingerspelled", so any condensed strokes that are _partly_-fingerspelled have been left as-is in `condensed-strokes.json`.

### CODE REVIEW

**Comment by didoesdigital** [comment]
This is excellent @paulfioravanti , thank you very much.

**Comment by didoesdigital** [comment]
Unfortunately, my merging https://github.com/didoesdigital/steno-dictionaries/pull/553 has caused conflicts. As you are more familiar with what you've added here @paulfioravanti , would you mind terribly doing the conflict resolution?

**Comment by paulfioravanti** [comment]
@didoesdigital done :+1:

**Comment by didoesdigital** [comment]
Thanks again @paulfioravanti ! 👏

**Pull request merged**
