### PR TITLE
Add AU with extra stroke entries

### PR DESCRIPTION
**Pull request by paulfioravanti**
I'm not sure entirely about the validity of these entries submitted, but I'm proposing them as quality-of-life changes so that when you stroke "endeavour", "saviour", "honourable", and "splendour", you get the visual feedback of seeing the correct US spelling of the word before using the `A*U` outline to modify them into Australian English.

The change of `"HOPB/RABL/A*U": "honourable"` from the fingerspelling might be a bit of an issue as the change is essentially introducing a dependency to a word that appears in Typey Type to the `dict-en-AU-with-extra-stroke.json` dictionary, but there are plenty of entries that already do have that dependency; I figure that anyone doing Typey Type is going to currently need that dictionary anyway to get through some of the exercises, and so the benefit of not having to fingerspell can be considered to outweigh the necessity of an external dictionary you'd already be using anyway.

### CODE REVIEW

**Comment by paulfioravanti** [comment]
I was going to add potential `HON/ORD/A*U` and `HO*RPBS/A*U` entries for "honoured" and "honours", but after having a look at [Notes on Design of and Changes in the Australian English with Extra Strokes Dictionary](https://github.com/didoesdigital/steno-dictionaries#notes-on-design-of-and-changes-in-the-australian-english-with-extra-strokes-dictionary), I'm not so sure anymore, nor am I entirely sure about the entire contents of this PR.

I would have thought that rules like

> Add "U" to O*R/A*U or TPHOR/A*U strokes for "nour" endings in words such as "honour" e.g. "HOPB/TPHOUR/A*U": "honour"

would be appropriate for `dict-en-AU.json`, but not for `dict-en-AU-with-extra-stroke.json` since the latter is meant to use the `A*U` suffix as a modifier to US Plover entries. What am I mis-understanding?

**Comment by paulfioravanti** [comment]
Merge conflicts resolved ✅

**Comment by didoesdigital** [comment]
Whoops, I got a little too excited there when I saw you'd resolved conflicts and merged it without reviewing the PR 🤦‍♀️

**Comment by didoesdigital** [comment]
Ok, there's a lot going on here.

Given the dependency you point out, and the number of British English spellings in Project Gutenberg, let's add update the note to [Typey Type's dictionaries index page](https://didoesdigital.com/typey-type/dictionaries) to recommend adding the AU dict for doing the Gutenberg lesson.

I removed the `dict-en-AU.json` when the maintenance got too high and I was realistically only using the -with-extra-strokes dictionary. I need to update the README accordingly.

> I would have thought that rules like

> > Add "U" to O\*R/AU or TPHOR/A\*U strokes for "nour" endings in words such as "honour" e.g. "HOPB/TPHOUR/A\*U": "honour"

> would be appropriate for dict-en-AU.json, but not for dict-en-AU-with-extra-stroke.json since the latter is meant to use the A\*U suffix as a modifier to US Plover entries. What am I mis-understanding?

Good catch. We could remove the `U` in entries like `"HOPB/O*UR/A*U": "honour",` (becomes `"HOPB/O*R/A*U": "honour",`) and `"HO*URPB/A*U": "honour",` (becomes `"HO*RPB/A*U": "honour",`).

**Comment by didoesdigital** [comment]
I also noticed https://github.com/didoesdigital/steno-dictionaries/issues/454

**Comment by didoesdigital** [comment]
Issue added to update dictionaries page: https://github.com/didoesdigital/typey-type/issues/26

**Comment by didoesdigital** [comment]
Issue for the README: https://github.com/didoesdigital/steno-dictionaries/issues/455

**Pull request merged**
