### PR TITLE
Change strokes for "access" and "excess" to their two-stroke counterparts.

### PR DESCRIPTION
**Pull request by paulfioravanti**
In Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), the strokes for the word "access" are now listed as:

KPES
ABG/ES
ABG/SES
ABGS/ES
ABG/SESZ
ABGS/SES

This makes the entry in Typey Type un-stroke-able using the current hint, so this PR proposes to change the stroke for "access" from `SESZ` to `KPES`, and remove `KPES`-related entries currently used for the word "excess" (they still exist under the `KP*ES` stroke, among others).

### CODE REVIEW

**Comment by didoesdigital** [comment]
The briefs around "access", "excess" and similar have inconsistencies so I struggle to suggest good, consistent strokes here. I've made a suggestion for changes to Plover dictionary: https://github.com/openstenoproject/plover/issues/400#issuecomment-394204080

I try to avoid getting ahead of issue 400 or varying too much from Plover but that lot was a mess.

The only changes I'd really feel comfortable making here would be hiding `SESZ` for now and showing the long form `ABG/SES` or fingerspelling it.

**Comment by paulfioravanti** [comment]
> The only changes I'd really feel comfortable making here would be hiding SESZ for now and showing the long form ABG/SES or fingerspelling it.

Totally understand. Would those feelings then extend to changing the entry for "excess" to the long form `EBG/SES` as well?

If so, perhaps it's then worth reverting the changes made here to `dict.json` and `briefs.json`, and just change the entries for "access" and "excess" in the `top-*.json` dictionaries to their two-stroke entries so they can be stroked in Typey Type...?

**Comment by paulfioravanti** [comment]
@didoesdigital great, done!

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti !

**Pull request merged**
