### PR TITLE
Mark stroke TRABGS for 'transaction' as a mis-stroke

### PR DESCRIPTION
**Pull request by paulfioravanti**
In Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), there is no entry for the stroke `TRABGS` to mean "transaction" (it instead outputs "traction"). Therefore, this PR aims to:

- Mark stroke `TRABGS` for "transaction" as a mis-stroke in the dictionaries
- Change the Typey-Type stroke for it to the correct `TKRABGS`

### CODE REVIEW

**Comment by didoesdigital** [comment]
Thanks for the PR, @paulfioravanti. Something's not adding up here though. I'm seeing `plover/assets/main.json:140496:1:"TRABGS": "traction",` — am I looking at something different to you?

Phonetically, I would expect `TRABGS` without the `K` to be used to the "tr" sound in "traction" and I would not expect `TKRABGS` with a `K` to use a "dr" sound in "traction".

**Comment by paulfioravanti** [comment]
Sorry, I should have been more specific and put a link to the problem entry. The issue is that the current dictionaries, there is a stroke for `TRABGS` as "transaction" (in both `dict.json` and `top-10000-project-gutenberg-words.json`)

https://github.com/didoesdigital/steno-dictionaries/blob/c057ce8e7a1a43e0593f627eb9b43f0d09f79d85/dictionaries/top-10000-project-gutenberg-words.json#L6923

So, yes, `TRABGS` for "traction" is correct, and this should be added to `dict.json` as it is not currently there, but I think `TRABGS` should be removed from `dict.json` and marked as a mis-stroke.

**Comment by didoesdigital** [comment]
Oh, I was paying attention to the strokes, not the words, and read it as "traction" repeatedly, instead of seeing the extra "nsa" in "transaction".

I think we want to:

- Add the missing `dict.json` entry for `"TRABGS": "traction",`
- Remove the `dict.json` entry for `"TRABGS": "transaction",`
- Possibly add a `bad-habits.json` entry for `"TRABGS": "transaction",`—might cause the same issue as https://github.com/didoesdigital/steno-dictionaries/pull/89#issuecomment-581707029
- Add one of `"T-RPBS": "transaction",`, `"TR-PBS": "transaction",`, `"TKRABGS": "transaction",`, `"TR*BGS": "transaction",`, or `"TRA*FBGS": "transaction",` for "transaction" to `dict.json` and `top-10000-project-gutenberg-words.json` to match the latest Plover dictionary, where you've proposed to choose `TKRABGS`.

Is that right?

**Comment by paulfioravanti** [comment]
> - Add the missing dict.json entry for "TRABGS": "traction",
> - Remove the dict.json entry for "TRABGS": "transaction",

Sounds good

> - Possibly add a bad-habits.json entry for "TRABGS": "transaction",—might cause the same issue as #89 (comment)

I'll probably have to leave it up to your best judgement, but I'm guessing that if https://github.com/didoesdigital/steno-dictionaries/pull/89#issuecomment-581707029 is a potential problem, and this problem is also of the same ilk, then perhaps it may be worth not adding `"TRABGS": "transaction",` to `bad-habits.json` at all.

> Add one of "T-RPBS": "transaction",, "TR-PBS": "transaction",, "TKRABGS": "transaction",, "TR*BGS": "transaction",, or "TRA*FBGS": "transaction", for "transaction" to dict.json and top-10000-project-gutenberg-words.json to match the latest Plover dictionary, where you've proposed to choose TKRABGS.

- For `top-10000-project-gutenberg-words.json` I'd keep with my proposal for `"TKRABGS": "transaction"`
- For `dict.json`, I'm guessing that since it's the dictionary that should contain all valid strokes for a word, then the addition of the strokes that are not currently in there from the list you provided should be the course of action. Specifically:
  - Add `"T-RPBS": "transaction",`, `"TR-PBS": "transaction",` to `dict.json` (the others are already in `dict.json`)

**Comment by didoesdigital** [comment]
@paulfioravanti that all sounds good to me

**Comment by paulfioravanti** [comment]
Done!

**Pull request merged**
